[build]
  command = "npx prisma generate && npm run build"
  publish = "build/client"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SHOPIFY_API_KEY,SCOPES"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://admin.shopify.com https://*.myshopify.com;"
    X-Frame-Options = "ALLOWALL"