# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "754341ccac733ecf4f62d1f6bd120d1e"
name = "Product Optimization Engine"
application_url = "https://phoenix-rise-flow.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_inventory,read_legal_policies,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_shipping,read_themes,write_content,write_files,write_inventory,write_products,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://phoenix-rise-flow.vercel.app/auth/callback",
  "https://phoenix-rise-flow.vercel.app/auth/shopify/callback",
  "https://phoenix-rise-flow.vercel.app/api/auth/callback"
]
