# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74aaa1e85b8da0ed82e29488842aab5f"
name = "Phoenix Flow Main"
application_url = "https://phoenix-rise-flow.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_inventory,read_legal_policies,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_shipping,read_themes,write_content,write_files,write_inventory,write_products,write_themes"

[auth]
redirect_urls = [
  "https://phoenix-rise-flow.vercel.app/auth/callback",
  "https://phoenix-rise-flow.vercel.app/auth/shopify/callback",
  "https://phoenix-rise-flow.vercel.app/api/auth/callback"
]
