name = "phoenix-rise-flow"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"


[[kv_namespaces]]
binding = "SESSION_KV"
id = "00d8647454174cfe8b5feb6e0023c698"
