name = "merchant-co-pilot-workstation"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[vars]
SHOPIFY_API_KEY = "ea7d669014bc192a3d3587fe2baa34a2"
APP_URL = "https://ironphoenixflow.com"
SHOPIFY_API_SECRET = ""
SCOPES = "read_products,write_products,write_content"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "00d8647454174cfe8b5feb6e0023c698"
